id: P009243
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W25138
  title: ཉམས་ལྡན་སོར་མོས་རྒྱུད་སྟོང་དཀྲོལ་བའི་ལས་འཕྲོ
  author: ''
  volumes:
    c44dc50abf2043909b7ede78fae5ccae:
      image_group_id: I1PD346
      title: ''
      volume_number: 1
      total_pages: 128
      base_file: v001.txt
